### ISSUE TITLE
Crash with GTCEu 2.7.2

### ISSUE THREAD

**Issue by Anthonity** [Nomi-CEu/gregtech-drawers#2]
The mod crashes with GTCEu 2.7.2
[crash-2023-07-18_11.28.14-client.txt](https://github.com/Nomi-CEu/gregtech-drawers/files/12078808/crash-2023-07-18_11.28.14-client.txt)

**Comment by IntegerLimit** [comment]
It actually just crashes. (Didn't in dev env)

Fixing now.

**Comment by IntegerLimit** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/gregtech-drawers/files/4661741.
